name: Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,6,8,10,12,14,16,18,20,22 * * *'

permissions:
  actions: write
  contents: read

jobs:
  steps:
    runs-on: ubuntu-latest
    name: Post

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Post
      id: myPost
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://public-ubiservices.ubi.com/v3/profiles/sessions'
        method: 'POST'
        customHeaders: '{"Ubi-AppId": "${{ secrets.Ubi_AppId }}","Authorization":"${{ secrets.Authorization }}","Content-Type":"application/json","Ubi-RequestedPlatformType":"uplay","User-Agent":"Massgate"}'

    - name: Save
      uses: rayhu/save-secret-as-file@v1
      with:
        secret: ${{ steps.myPost.outputs.response }}
        filename: post.json

    - name: Push
      run: |
        git config user.name github-actions
        git config user.email actions@github.com
        git add post.json
        git commit -m "Update post.json"
        git push

    - name: Disable
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const workflowPath = '${{ github.workflow_ref }}'.split('/').pop();
          await github.rest.actions.disableWorkflow({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: workflowPath
          });            
          console.log(`Disable workflow：${workflowPath}`);
