name: Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  steps:
    runs-on: ubuntu-latest
    name: Post

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Post
      id: myPost
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://public-ubiservices.ubi.com/v3/profiles/sessions'
        method: 'POST'
        customHeaders: '{"Ubi-AppId": "${{ secrets.Ubi_AppId }}","Authorization":"${{ secrets.Authorization }}"}'

    - name: Update
      uses: restackio/update-json-values-action@v1.0.0
      with:
        file: post.json
        values: "${{ steps.myPost.outputs.response }}"
