name: Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'

jobs:
  steps:
    runs-on: ubuntu-latest
    name: Post

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Post
      id: myPost
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://public-ubiservices.ubi.com/v3/profiles/sessions'
        method: 'POST'
        customHeaders: '{"Ubi-AppId": "${{ secrets.Ubi_AppId }}","Authorization":"${{ secrets.Authorization }}"}'

    - name: Save
      uses: rayhu/save-secret-as-file@v1
      with:
        secret: ${{ steps.myPost.outputs.response }}
        filename: post.json

    - name: Push
      run: |
        git config user.name github-actions
        git config user.email 269442033@qq.com
        git add post.json
        git commit -m "Update post.json"
        git push
