name: Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '15 12,16,18,20,22 * * 2'
    - cron: '10 0,2,4,5,6,7,8,9,10,11,12,15,18,20,22 * * 3'
    - cron: '10 0,2,4,5,6,7,8,9,10,11,12,15,18,22 * * 4'


jobs:
  steps:
    runs-on: ubuntu-latest
    name: Sync

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update gear
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://rubenalamina.mx/division/gear.json
        file_in_repo: gear.json

    - name: Update weapon
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://rubenalamina.mx/division/weapons.json
        file_in_repo: weapon.json

    - name: Update mod
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://rubenalamina.mx/division/mods.json
        file_in_repo: mod.json
