name: Sync

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '15 * * * 0,1,5,6'
  #   - cron: '15 * * * 2,3,4'
  
jobs:
  steps:
    runs-on: ubuntu-latest
    name: Sync

    steps:
    # - name: Checkout
    #   uses: actions/checkout@v4

    - name: GET request
      id: get-request
      uses: satak/webrequest-action@master
      with:
        url: https://rubenalamina.mx/division/gear.json
        method: GET

    - name: Display
      shell: pwsh
      run: |
        $output = '${{ steps.get-request.outputs.output }}' | ConvertFrom-Json
        Write-Host "$($output.data)"
        $output.data -eq 1
        echo ${{ output.data }} > gear.json

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: pack
        path: ~/gear.json

    - name: Update
      run: |
        git add gear.json
        git commit -m "Update"
        git push
