name: Sync

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '15 * * * 0,1,5,6'
  #   - cron: '15 * * * 2,3,4'
  
jobs:
  steps:
    runs-on: ubuntu-latest
    name: Sync

    steps:
    # - name: Checkout
    #   uses: actions/checkout@v4

    - name: Response
      uses: satak/webrequest-action@master
      with:
        url: https://rubenalamina.mx/division/gear.json
        method: GET

    - name: Display
      run: |
        $output = '${{ steps.Response.outputs.output }}' | ConvertFrom-Json
        Write-Host "Time from output $($output.time) statusCode $($output.statusCode) data $($output.data)"

    # - name: Upload
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: pack
    #     path: ~/*.json

    # - name: Update
    #   run: |
    #     git config user.name github-actions
    #     git config user.email github-actions@github.com
    #     git add .
    #     git commit -m "Update"
    #     git push
