name: Sync

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '15 * * * 0,1,5,6'
  #   - cron: '15 * * * 2,3,4'
  
permissions:
  contents: write

jobs:
  steps:
    runs-on: ubuntu-latest
    name: Sync

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update gear
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://rubenalamina.mx/division/gear.json
        file_in_repo: gear.json

    - name: Update weapon
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://rubenalamina.mx/division/weapons.json
        file_in_repo: weapon.json

    - name: Update mod
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://rubenalamina.mx/division/mods.json
        file_in_repo: mod.json